"""add roles

Revision ID: 03295cb7f826
Revises: e679c0fadc33
Create Date: 2025-05-07 17:06:18.178254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03295cb7f826'
down_revision = 'e679c0fadc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('Customer', 'Admin', 'Staff', 'Seller', name='user_roles'),
               type_=sa.Enum('Customer', 'Seller', name='user_roles', native_enum=False, create_constraint=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('Customer', 'Seller', name='user_roles', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('Customer', 'Admin', 'Staff', 'Seller', name='user_roles'),
               existing_nullable=True)

    # ### end Alembic commands ###
