"""add valid_from to valid_to to discounts

Revision ID: 4a34a142d4b7
Revises: 03295cb7f826
Create Date: 2025-05-09 23:13:11.499687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a34a142d4b7'
down_revision = '03295cb7f826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('valid_to', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_column('valid_to')
        batch_op.drop_column('valid_from')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
