"""add admin to role

Revision ID: c1ce2693d123
Revises: fde8c9958e78
Create Date: 2025-05-07 04:29:26.470104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ce2693d123'
down_revision = 'fde8c9958e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
