"""add staff to role

Revision ID: e679c0fadc33
Revises: c1ce2693d123
Create Date: 2025-05-07 04:48:58.616679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e679c0fadc33'
down_revision = 'c1ce2693d123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
