"""try fix error

Revision ID: fa0c0d4c01eb
Revises: 15b601e5cd21
Create Date: 2025-05-03 09:30:38.703055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0c0d4c01eb'
down_revision = '15b601e5cd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
