"""dix discount relation

Revision ID: fde8c9958e78
Revises: 96e9a0e00941
Create Date: 2025-05-06 17:26:19.710022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde8c9958e78'
down_revision = '96e9a0e00941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('products_discounts_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'discounts', ['discount_id'], ['discount_id'])
        batch_op.drop_column('discounts_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discounts_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_discounts_id_fkey', 'discounts', ['discounts_id'], ['discount_id'])
        batch_op.drop_column('discount_id')

    # ### end Alembic commands ###
